import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface PayoutType {
  id: String;
  group: String;
  username: String;
  paid: Number;
  unpaid: Number;
  rate: Number;
  paidRef: Number;
  unpaidRef: Number;
  visits: Number;
  id_verify?: Date;
  status: Boolean;
}

export default function PayoutTable({ data }: { data: PayoutType[] }) {
  return (
    <Table className="rounded-md overflow-hidden">
      <TableHeader className="bg-gray-50 shadow-md">
        <TableRow>
          <TableHead>Payout ID</TableHead>
          <TableHead>Amount</TableHead>
          <TableHead>Affiliate</TableHead>
          <TableHead>Referrals</TableHead>
          <TableHead>Generated by</TableHead>
          <TableHead>Payout method</TableHead>
          <TableHead>Payout account</TableHead>
          <TableHead>Status</TableHead>
          <TableHead>Action</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {data.map((row: PayoutType, i: number) => (
          <TableRow key={i}>
            <TableCell className="font-medium">{row.name}</TableCell>
            <TableCell>{row.id}</TableCell>
            <TableCell>{row.group}</TableCell>
            <TableCell>{row.username}</TableCell>
            <TableCell>${row.paid.toString()}</TableCell>
            <TableCell>${row.unpaid.toString()}</TableCell>
            <TableCell>{row.rate.toString()}%</TableCell>
            <TableCell>${row.paidRef.toString()}</TableCell>
            <TableCell>${row.unpaidRef.toString()}</TableCell>
            <TableCell>{row.visits.toString()}</TableCell>
            <TableCell>{row?.id_verify?.toString()?.slice(0, 10)}</TableCell>
            <TableCell>{row.status ? "Active" : "Deactivate"}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
