import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface PayoutType {
  id: String;
  amount: Number;
  affiliate: String;
  referrals: String;
  generated: String;
  method: String;
  account: String;
  status: Boolean;
  date: Date;
  action: String;
}

export default function PayoutTable({ data }: { data: PayoutType[] }) {
  return (
    <Table className="rounded-md overflow-hidden">
      <TableHeader className="bg-gray-50 shadow-md">
        <TableRow>
          <TableHead>Payout ID</TableHead>
          <TableHead>Amount</TableHead>
          <TableHead>Affiliate</TableHead>
          <TableHead>Referrals</TableHead>
          <TableHead>Generated by</TableHead>
          <TableHead>Payout method</TableHead>
          <TableHead>Payout account</TableHead>
          <TableHead>Status</TableHead>
          <TableHead>Action</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {data.map((row: PayoutType, i: number) => (
          <TableRow key={i}>
            <TableCell className="font-medium">{row.id}</TableCell>
            <TableCell>{row.amount.toString()}</TableCell>
            <TableCell>{row.affiliate}</TableCell>
            <TableCell>{row.referrals}</TableCell>
            <TableCell>{row.generated}</TableCell>
            <TableCell>{row.method}</TableCell>
            <TableCell>{row.account}</TableCell>
            <TableCell>{row.date.toISOString().slice(0, 10)}</TableCell>
            <TableCell>{row.action}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
