import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface DashboardType {
  id: String;
}

export default function DashboardTable({ data }: { data: DashboardType[] }) {
  return (
    <Table className="rounded-md overflow-hidden">
      <TableHeader className="bg-gray-50 shadow-md">
        <TableRow>
          <TableHead>Dashboard ID</TableHead>
          <TableHead>Amount</TableHead>
          <TableHead>Affiliate</TableHead>
          <TableHead>Dashboards</TableHead>
          <TableHead>Generated by</TableHead>
          <TableHead>Dashboard method</TableHead>
          <TableHead>Dashboard account</TableHead>
          <TableHead>Status</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {data.map((row: DashboardType, i: number) => (
          <TableRow key={i}>
            <TableCell className="font-medium">{row.id}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
